### ISSUE TITLE
Rejoin channel that requires you to be registered

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#33]
> This channel requires that you have registered and identified yourself with the network's nickname registration services (e.g. NickServ). Please see the documentation of this network's nickname registration services that should be found in the MOTD (/motd to display it).

After I identified, it should rejoin the channel automatically (or try to do so at least once).

**Comment by Ascrod** [comment]
It sounds like nickserv identification is not completing by the time the client starts joining channels automatically. If that is the case, you will have to rejoin them manually.

This can probably be worked around by using SASL to identify *during* the connection process (if the server supports it), either using the [existing plugin](https://freenode.net/static/files/cz_sasl.js) or waiting until I can finish working on native SASL support. :wink:

Out of curiosity, are you rejoining channels because they were already open before a disconnect, or are you joining channels with the auto-perform list?

**Comment by Smile4ever** [comment]
It sounds like nickserv identification is not completing by the time the client starts joining channels automatically. If that is the case, you will have to rejoin them manually.
> That's right, that's what's happening.

Freenode supports SASL, so I will configure it.

I am joining channels with the auto-perform (startup) list (right click on the channel/tab -> open at startup).
