### ISSUE TITLE
Move switch text direction from the IRC menu to the View menu

### ISSUE THREAD

**Issue by Smile4ever** [Ascrod/ambassador#43]
A more logical place. It has nothing to do with IRC itself.

**Comment by Ascrod** [comment]
I was debating on whether to implement this or not. There are several items in the IRC menu that don't necessarily have to do with IRC, but are there because the IRC menu more or less matches up with the context menus for tabs and the output window. However, switching the text direction is not as commonly used like the rest of the IRC menu - it is a set-and-forget option, more in line with the rest of the View menu.

So, in addition to moving this option to the View menu (probably under the Font Family item), it should also be removed from the context menus.
