### ISSUE TITLE
Wired application name in WIndows Sound Mixer

### ISSUE THREAD

**Issue by kn-yami** [Ascrod/ambassador#55]
It looks like this:
![Windows Sound Mixer](https://user-images.githubusercontent.com/34216515/50374603-ec85ea80-05f0-11e9-8094-08cef56bb1c9.png)

**Comment by Ascrod** [comment]
It looks like the revision isn't being preprocessed as part of the `brandFullName` string property in the brand localization files. One option would be to preprocess these files to populate the revision number correctly. Another option would be to just remove the version number from the property altogether. I'm leaning toward the latter option since no UXP application includes the revision in the brand name.

**Comment by kn-yami** [comment]
Removing the revision sounds better to me.
